terms:
  - term: "Charter College of Education"
  - term: "College of Arts and Letters"
  - term: "College of Business and Economics"
  - term: "College of Engineering, Computer Science, and Technology"
  - term: "College of Ethnic Studies"
  - term: "College of Natural and Social Sciences"
  - term: "College of Professional and Global Education"
  - term: "Honors College"
  - term: "Rongxiang Xu College of Health and Human Services"
  - term: "University Library"
