terms:
  - term: "Business Administration"
  - term: "Education, Health and Human Services"
  - term: "Humanities, Arts, and Behavioral and Social Sciences"
  - term: "Science, Technology, Engineering, and Mathematics"
  - term: "University Library"
