terms:
  - term: "Arts and Letters"
  - term: "Education"
  - term: "Engineering"
  - term: "Fowler College of Business Administration"
  - term: "Health and Human Services"
  - term: "Imperial Valley Campus"
  - term: "Professional Studies and Fine Arts"
  - term: "Sciences"
  - term: "Division of Undergraduate Studies"
