terms:
  - term: "College of Business (COB)"
  - term: "College of Education (CED)"
  - term: "College of Engineering (COE)"
  - term: "College of Health & Human Services (CHHS)"
  - term: "College of Liberal Arts (CLA)"
  - term: "College of Natural Sciences & Mathematics (CNSM)"
  - term: "College of Professional & International Education (CPIE)"
  - term: "College of the Arts (COTA)"
  - term: "University Programs"
