terms:
  - term: "Business Administration"
  - term: "Education, Health & Human Services"
  - term: "Humanities, Arts, Behavioral & Social Sciences"
  - term: "Science, Technology, Engineering & Mathematics"
  - term: "University Library"
