terms:
  - term: "Continuous"
  - term: "Discrete"
  - term: "Graph Based Data"
  - term: "Image Data"
  - term: "Interval"
  - term: "Mixed"
  - term: "Nominal"
  - term: "Ordinal"
  - term: "Qualitative"
  - term: "Quantitative"
  - term: "Ratio"
  - term: "Sequence Data"
  - term: "Sequential / Temporal Data"
  - term: "Spatial Data"
  - term: "Time Series Data"
  - term: "Other"
