terms:
  - term: "Department of Accounting"
    college: "College of Business and Economics"
  - term: "Department of Anthropology"
    college: "College of Natural and Social Sciences"
  - term: "Department of Art"
    college: "College of Arts and Letters"
  - term: "Department of Asian and Asian-American Studies"
    college: "College of Ethnic Studies"
  - term: "Department of Biological Sciences"
    college: "College of Natural and Social Sciences"
  - term: "Department of Chemistry and Biochemistry"
    college: "College of Natural and Social Sciences"
  - term: "Department of Chicana(o) and Latina(o) Studies"
    college: "College of Ethnic Studies"
  - term: "Department of Child and Family Studies"
    college: "Rongxiang Xu College of Health and Human Services"
  - term: "Department of Civil Engineering"
    college: "College of Engineering, Computer Science, and Technology"
  - term: "Department of Communication Disorders"
    college: "Rongxiang Xu College of Health and Human Services"
  - term: "Department of Communication Studies"
    college: "College of Arts and Letters"
  - term: "Department of Computer Science"
    college: "College of Engineering, Computer Science, and Technology"
  - term: "Department of Economics and Statistics"
    college: "College of Business and Economics"
  - term: "Department of Electrical and Computer Engineering"
    college: "College of Engineering, Computer Science, and Technology"
  - term: "Department of English"
    college: "College of Arts and Letters"
  - term: "Department of Finance, Law and Real Estate"
    college: "College of Business and Economics"
  - term: "Department of Geosciences and Environment"
    college: "College of Natural and Social Sciences"
  - term: "Department of History"
    college: "College of Natural and Social Sciences"
  - term: "Department of Information Systems"
    college: "College of Business and Economics"
  - term: "Department of Liberal Studies"
    college: "College of Arts and Letters"
  - term: "Department of Management"
    college: "College of Business and Economics"
  - term: "Department of Marketing"
    college: "College of Business and Economics"
  - term: "Department of Mathematics"
    college: "College of Natural and Social Sciences"
  - term: "Department of Mechanical Engineering"
    college: "College of Engineering, Computer Science, and Technology"
  - term: "Department of Modern Languages and Literatures"
    college: "College of Arts and Letters"
  - term: "Department of Music"
    college: "College of Arts and Letters"
  - term: "Department of Pan-African Studies"
    college: "College of Ethnic Studies"
  - term: "Department of Philosophy"
    college: "College of Arts and Letters"
  - term: "Department of Physics and Astronomy"
    college: "College of Natural and Social Sciences"
  - term: "Department of Political Science"
    college: "College of Natural and Social Sciences"
  - term: "Department of Psychology"
    college: "College of Natural and Social Sciences"
  - term: "Department of Public Health"
    college: "Rongxiang Xu College of Health and Human Services"
  - term: "Department of Sociology"
    college: "College of Natural and Social Sciences"
  - term: "Department of Technology"
    college: "College of Engineering, Computer Science, and Technology"
  - term: "Department of Television, Film, and Media Studies"
    college: "College of Arts and Letters"
  - term: "Department of Theatre and Dance"
    college: "College of Arts and Letters"
  - term: "Division of Applied and Advanced Studies in Education"
    college: "Charter College of Education"
  - term: "Division of Curriculum and Instruction"
    college: "Charter College of Education"
  - term: "Division of Special Education and Counseling"
    college: "Charter College of Education"
  - term: "Patricia A. Chin School of Nursing"
    college: "Rongxiang Xu College of Health and Human Services"
  - term: "Program in Intercultural Proficiency"
    college: "Rongxiang Xu College of Health and Human Services"
  - term: "Program in Latin American Studies"
    college: "College of Natural and Social Sciences"
  - term: "Program in Youth Agency Administration"
    college: "Rongxiang Xu College of Health and Human Services"
  - term: "Programs in Interdisciplinary Business"
    college: "College of Business and Economics"
  - term: "Programs in International Business"
    college: "College of Business and Economics"
  - term: "Programs in Natural Science"
    college: "College of Natural and Social Sciences"
  - term: "School of Criminal Justice and Criminalistics"
    college: "Rongxiang Xu College of Health and Human Services"
  - term: "School of Kinesiology and Nutritional Science"
    college: "Rongxiang Xu College of Health and Human Services"
  - term: "School of Social Work"
    college: "Rongxiang Xu College of Health and Human Services"
  - term: "University Library"