terms:
  - term: "Academic Senate"
  - term: "Administration"
  - term: "Culture and Communication"
    college: "Letters and Science"
  - term: "Engineering Technology"
    college: "Engineering"
  - term: "Global Studies and Maritime Affairs"
    college: "Letters and Science"
  - term: "International Business and Logistics"
    college: "Maritime Transportation, Logistics & Management"
  - term: "Library"
  - term: "Marine Transportation"
    college: "Maritime Transportation, Logistics & Management"
  - term: "Mechanical Engineering"
    college: "Engineering"
  - term: "Naval Science"
    college: "Maritime Transportation, Logistics & Management"
  - term: "Office of the President"
  - term: "Sciences and Mathematics"
    college: "Letters and Science"
