terms:
  - term: "Department of Art"
  - term: "Department of Communication Studies"
  - term: "Department of English"
  - term: "Department of Liberal Studies"
  - term: "Department of Modern Languages and Literatures"
  - term: "Department of Music"
  - term: "Department of Philosophy"
  - term: "Department of Television, Film, and Media Studies"
  - term: "Department of Theatre and Dance"
  - term: "Department of Accounting"
  - term: "Department of Economics and Statistics"
  - term: "Department of Finance, Law and Real Estate"
  - term: "Department of Information Systems"
  - term: "Department of Management"
  - term: "Department of Marketing"
  - term: "Programs in Interdisciplinary Business"
  - term: "Programs in International Business"
  - term: "Division of Applied and Advanced Studies in Education"
  - term: "Division of Curriculum and Instruction"
  - term: "Division of Special Education and Counseling"
  - term: "Department of Civil Engineering"
  - term: "Department of Computer Science"
  - term: "Department of Electrical and Computer Engineering"
  - term: "Department of Mechanical Engineering"
  - term: "Department of Technology"
  - term: "Department of Child and Family Studies"
  - term: "Department of Communication Disorders"
  - term: "School of Criminal Justice and Criminalistics"
  - term: "Department of Public Health"
  - term: "School of Kinesiology and Nutritional Science"
  - term: "Patricia A. Chin School of Nursing"
  - term: "School of Social Work"
  - term: "Program in Intercultural Proficiency"
  - term: "Program in Youth Agency Administration"
  - term: "Department of Anthropology"
  - term: "Department of Asian and Asian-American Studies"
  - term: "Department of Biological Sciences"
  - term: "Department of Chemistry and Biochemistry"
  - term: "Department of Chicana(o) and Latina(o) Studies"
  - term: "Department of Geosciences and Environment"
  - term: "Department of History"
  - term: "Department of Mathematics"
  - term: "Department of Pan-African Studies"
  - term: "Department of Physics and Astronomy"
  - term: "Department of Political Science"
  - term: "Department of Psychology"
  - term: "Department of Sociology"
  - term: "Program in Latin American Studies"
  - term: "Programs in Natural Science"
