terms:
  - term: "Adelante"
    college:
      - "Undergraduate Education"
      - "Graduate Studies"
  - term: "Agriculture"
    college: "Agriculture"
  - term: "Anthropology"
    college: "Behavioral and Social Sciences"
  - term: "Applied Computer Graphics"
    college: "Engineering, Computer Science and Construction Management"
  - term: "Art and Art History"
    college: "Humanities and Fine Arts"
  - term: "Biological Sciences"
    college: "Natural Sciences"
  - term: "Chemistry and Biochemistry"
    college: "Natural Sciences"
  - term: "Child Development"
    college: "Behavioral and Social Sciences"
  - term: "Civil Engineering"
    college: "Engineering, Computer Science and Construction Management"
  - term: "Communication Arts and Sciences"
    college: "Communication and Education"
  - term: "Comparative Religion and Humanities"
    college: "Humanities and Fine Arts"
  - term: "Computer Science"
    college: "Engineering, Computer Science and Construction Management"
  - term: "Concrete Industry Management"
    college: "Engineering, Computer Science and Construction Management"
  - term: "Construction Management"
    college: "Engineering, Computer Science and Construction Management"
  - term: "Earth and Environmental Sciences"
    college: "Natural Sciences"
  - term: "Economics"
    college: "Behavioral and Social Sciences"
  - term: "Education"
    college: "Communication and Education"
  - term: "Electrical and Computer Engineering"
    college: "Engineering, Computer Science and Construction Management"
  - term: "English"
    college: "Humanities and Fine Arts"
  - term: "Geography and Planning"
    college: "Behavioral and Social Sciences"
  - term: "History"
    college: "Humanities and Fine Arts"
  - term: "Honors"
    college: "Undergraduate Education"
  - term: "Information Systems, Finance, and Accounting"
    college: "Business"
  - term: "Interdisciplinary Studies"
    college: "Graduate Studies"
  - term: "Journalism and Public Relations"
    college: "Communication and Education"
  - term: "Kinesiology"
    college: "Communication and Education"
  - term: "Languages and Cultures"
    college: "Humanities and Fine Arts"
  - term: "Liberal Studies"
    college: "Communication and Education"
  - term: "Management"
    college: "Business"
  - term: "Marketing"
    college: "Business"
  - term: "Mathematics and Statistics"
    college: "Natural Sciences"
  - term: "Mechanical and Mechatronic Engineering and Advanced Manufacturing"
    college: "Engineering, Computer Science and Construction Management"
  - term: "Media Arts, Design, and Technology"
    college: "Communication and Education"
  - term: "Meriam Library"
    college: "Meriam Library"
  - term: "Multicultural and Gender Studies"
    college: "Behavioral and Social Sciences"
  - term: "Music and Theatre"
    college: "Humanities and Fine Arts"
  - term: "Nursing"
    college: "Natural Sciences"
  - term: "Nutrition and Food Science"
    college: "Natural Sciences"
  - term: "Philosophy"
    college: "Humanities and Fine Arts"
  - term: "Physics"
    college: "Natural Sciences"
  - term: "Political Science and Criminal Justice"
    college: "Behavioral and Social Sciences"
  - term: "Psychology"
    college: "Behavioral and Social Sciences"
  - term: "Public Administration"
    college: "Behavioral and Social Sciences"
  - term: "Public Health and Health Services Administration"
    college: "Behavioral and Social Sciences"
  - term: "Recreation, Hospitality, and Parks Management"
    college: "Communication and Education"
  - term: "Science Education"
    college: "Natural Sciences"
  - term: "Social Science"
    college: "Behavioral and Social Sciences"
  - term: "Social Work"
    college: "Behavioral and Social Sciences"
  - term: "Sociology"
    college: "Behavioral and Social Sciences"
