terms:
  - term: "Anthropology"
    college: "Social Sciences"
  - term: "Biology"
    college: "Science and Technology"
  - term: "Business Administration"
    college: "Business and Economics"
  - term: "Communication and Media Studies"
    college: "Arts and Humanities"
  - term: "Computer and Engineering Science"
    college: "Science and Technology"
  - term: "Counseling"
    college: "Education"
  - term: "Cultural Resources Management"
    college: "Social Sciences"
  - term: "Early Childhood Education"
    college: "Education"
  - term: "Education"
    college: "Education"
  - term: "Electrical and Computer Engineering"
    college: "Science and Technology"
  - term: "Engineering Science"
    college: "Science and Technology"
  - term: "English"
    college: "Arts and Humanities"
  - term: "Film Studies"
    college: "Arts and Humanities"
  - term: "Global Wine Business"
    college: "Extended Education & International Education"
  - term: "History"
    college: "Social Sciences"
  - term: "Hutchins School of Liberal Studies"
    college: "Arts and Humanities"
  - term: "Interdisciplinary Studies"
  - term: "Kinesiology"
    college: "Science and Technology"
  - term: "Modern Languages and Literatures"
    college: "Extended Education & International Education"
  - term: "Nursing"
    college: "Science and Technology"
  - term: "Organization Development"
    college: "Extended Education & International Education"
  - term: "Political Science"
    college: "Social Sciences"
  - term: "Psychology"
    college: "Social Sciences"
  - term: "Public Administration"
    college: "Social Sciences"
  - term: "Purpose-Driven Business"
    college: "Business and Economics"
  - term: "Spanish"
    college: "Extended Education & International Education"
  - term: "University Library"
    college: "University Library"
  - term: "Wine Business"
    college: "Business and Economics"