terms:
  - term: "Accountancy"
    college: "Business"
  - term: "Anthropology"
    college: "Liberal & Creative Arts"
  - term: "Art"
    college: "Liberal & Creative Arts"
  - term: "Asian American Studies"
    college: "Ethnic Studies"
  - term: "Biology"
    college: "Science & Engineering"
  - term: "Broadcast and Electronic Communication Arts"
    college: "Liberal & Creative Arts"
  - term: "Business Administration"
    college: "Business"
  - term: "Business Analytics"
    college: "Business"
  - term: "Chemistry and Biochemistry"
    college: "Science & Engineering"
  - term: "Chinese"
    college: "Liberal & Creative Arts"
  - term: "Cinema Studies"
    college: "Liberal & Creative Arts"
  - term: "Classics"
    college: "Liberal & Creative Arts"
  - term: "Clinical Mental Health Counseling"
    college: "Health & Social Sciences"
  - term: "Communication Studies"
    college: "Liberal & Creative Arts"
  - term: "Communicative Disorders"
    college: "Education"
  - term: "Comparative and World Literature"
    college: "Liberal & Creative Arts"
  - term: "Computer Science"
    college: "Science & Engineering"
  - term: "Counseling"
    college: "Health & Social Sciences"
  - term: "Design"
    college: "Liberal & Creative Arts"
  - term: "Economics"
    college: "Business"
  - term: "Education"
    college: "Education"
  - term: "Education: Concentration in Special Education"
    college: "Education"
  - term: "Educational Leadership"
    college: "Education"
  - term: "Engineering"
    college: "Science & Engineering"
  - term: "English"
    college: "Liberal & Creative Arts"
  - term: "English: Creative Writing"
    college: "Liberal & Creative Arts"
  - term: "English: Teaching English to Speakers of Other Languages"
    college: "Liberal & Creative Arts"
  - term: "Ethnic Studies"
    college: "Ethnic Studies"
  - term: "Family & Consumer Sciences"
    college: "Health & Social Sciences"
  - term: "French"
    college: "Liberal & Creative Arts"
  - term: "Geography & Environment"
    college: "Science & Engineering"
  - term: "Geography"
    college: "Science & Engineering"
  - term: "Geosciences"
    college: "Science & Engineering"
  - term: "German"
    college: "Liberal & Creative Arts"
  - term: "Gerontology"
    college: "Health & Social Sciences"
  - term: "History"
    college: "Liberal & Creative Arts"
  - term: "Human Sexuality Studies"
    college: "Health & Social Sciences"
  - term: "Humanities"
    college: "Liberal & Creative Arts"
  - term: "Interdisciplinary Marine and Estuary Sciences"
    college: "Science & Engineering"
  - term: "International Relations"
    college: "Liberal & Creative Arts"
  - term: "Italian"
    college: "Liberal & Creative Arts"
  - term: "Japanese"
    college: "Liberal & Creative Arts"
  - term: "Kinesiology"
    college: "Health & Social Sciences"
  - term: "Mathematics"
    college: "Science & Engineering"
  - term: "Museum Studies"
    college: "Liberal & Creative Arts"
  - term: "Music"
    college: "Liberal & Creative Arts"
  - term: "Nursing"
    college: "Health & Social Sciences"
  - term: "Philosophy"
    college: "Liberal & Creative Arts"
  - term: "Physical Therapy"
    college: "Health & Social Sciences"
  - term: "Physics"
    college: "Science & Engineering"
  - term: "Political Science"
    college: "Liberal & Creative Arts"
  - term: "Psychology"
    college: "Science & Engineering"
  - term: "Public Administration"
    college: "Health & Social Sciences"
  - term: "Public Health"
    college: "Health & Social Sciences"
  - term: "Recreation, Parks & Tourism"
    college: "Health & Social Sciences"
  - term: "Social Work"
    college: "Health & Social Sciences"
  - term: "Spanish"
    college: "Liberal & Creative Arts"
  - term: "Special Education"
    college: "Education"
  - term: "Theatre Arts"
    college: "Liberal & Creative Arts"
  - term: "Women and Gender Studies"
    college: "Liberal & Creative Arts"
