terms:
 - term: "Anthropology"
   college: "Arts, Humanities, and Social Sciences"
 - term: "Art"
   college: "Arts, Humanities, and Social Sciences"
 - term: "Biological Sciences"
   college: "Natural Resources and Sciences"
 - term: "Biology"
   college: "Natural Resources and Sciences"
 - term: "Business"
   college: "Professional Studies"
 - term: "Chemistry"
   college: "Natural Resources and Sciences"
 - term: "Child Development"
   college: "Professional Studies"
 - term: "Communication"
   college: "Arts, Humanities, and Social Sciences"
 - term: "Computer Science"
   college: "Natural Resources and Sciences"
 - term: "Critical Race, Gender, and Sexuality Studies"
   college: "Arts, Humanities, and Social Sciences"
 - term: "Dance"
   college: "Arts, Humanities, and Social Sciences"
 - term: "Economics"
   college: "Professional Studies"
 - term: "Education"
   college: "Professional Studies"
 - term: "English"
   college: "Arts, Humanities, and Social Sciences"
 - term: "Environment & Community"
   college: "Arts, Humanities, and Social Sciences"
 - term: "Environmental Resources Engineering"
   college: "Natural Resources and Sciences"
 - term: "Environmental Science & Management"
   college: "Natural Resources and Sciences"
 - term: "Environmental Studies"
   college: "Arts, Humanities, and Social Sciences"
 - term: "Environmental Systems"
   college: "Natural Resources and Sciences"
 - term: "Film"
   college: "Arts, Humanities, and Social Sciences"
 - term: "Fisheries"
   college: "Natural Resources and Sciences"
 - term: "Fisheries Biology"
   college: "Natural Resources and Sciences"
 - term: "Forestry"
   college: "Natural Resources and Sciences"
 - term: "Forestry & Wildland Resources"
   college: "Natural Resources and Sciences"
 - term: "Geography"
   college: "Arts, Humanities, and Social Sciences"
 - term: "Geography, Environment & Spatial Analysis"
   college: "Arts, Humanities, and Social Sciences"
 - term: "Geology"
   college: "Natural Resources and Sciences"
 - term: "Globalization"
   college: "Arts, Humanities, and Social Sciences"
 - term: "History"
   college: "Arts, Humanities, and Social Sciences"
 - term: "International Studies"
   college: "Arts, Humanities, and Social Sciences"
 - term: "Journalism & Mass Communication"
   college: "Arts, Humanities, and Social Sciences"
 - term: "Journalism & Mass Communications"
   college: "Arts, Humanities, and Social Sciences"
 - term: "Kinesiology"
   college: "Professional Studies"
 - term: "Kinesiology & Recreation Administration"
   college: "Professional Studies"
 - term: "Leadership Studies"
   college: "Professional Studies"
 - term: "Mathematics"
   college: "Natural Resources and Sciences"
 - term: "Music"
   college: "Arts, Humanities, and Social Sciences"
 - term: "Native American Studies"
   college: "Arts, Humanities, and Social Sciences"
 - term: "Natural Resources"
   college: "Natural Resources and Sciences"
 - term: "Oceanography"
   college: "Natural Resources and Sciences"
 - term: "Philosophy"
   college: "Arts, Humanities, and Social Sciences"
 - term: "Physical Education"
   college: "Professional Studies"
 - term: "Physics"
   college: "Natural Resources and Sciences"
 - term: "Physics & Astronomy"
   college: "Natural Resources and Sciences"
 - term: "Politics"
   college: "Arts, Humanities, and Social Sciences"
 - term: "Psychology"
   college: "Professional Studies"
 - term: "Religious Studies"
   college: "Arts, Humanities, and Social Sciences"
 - term: "Social Science"
   college: "Arts, Humanities, and Social Sciences"
 - term: "Social Work"
   college: "Professional Studies"
 - term: "Sociology"
   college: "Arts, Humanities, and Social Sciences"
 - term: "Theatre Arts"
   college: "Arts, Humanities, and Social Sciences"
 - term: "Wildlife"
   college: "Natural Resources and Sciences"
 - term: "World Languages & Cultures"
   college: "Arts, Humanities, and Social Sciences"
