terms:
  - term: "Anthropology"
  - term: "Biology"
  - term: "Business Administration"
  - term: "Computer Science"
  - term: "Counseling"
  - term: "Cultural Resources Management"
  - term: "Education"
  - term: "Electrical Engineering Science"
  - term: "Engineering Science"
  - term: "English"
  - term: "Film Studies"
  - term: "History"
  - term: "Hutchins School of Liberal Studies"
  - term: "Interdisciplinary Studies Program"
  - term: "Library"
  - term: "Kinesiology"
  - term: "Modern Languages"
  - term: "Nursing"
  - term: "Organization Development"
  - term: "Political Science"
  - term: "Psychology"
  - term: "Public Administration"
