terms:
  - term: "Accounting and Finance"
    college: "College of Business Administration"
  - term: "Advanced Studies in Education"
    college: "College of Education, Kinesiology & Social Work"
  - term: "Anthropology, Geography, and Ethnic Studies"
    college: "College of the Arts, Humanities and Social Sciences"
  - term: "Art"
    college: "College of the Arts, Humanities and Social Sciences"
  - term: "Biological Sciences"
    college: "College of Science"
  - term: "Chemistry"
    college: "College of Science"
  - term: "Communication Studies"
    college: "College of the Arts, Humanities and Social Sciences"
  - term: "Computer Science"
    college: "College of Science"
  - term: "Criminal Justice"
    college: "College of the Arts, Humanities and Social Sciences"
  - term: "Doctor of Education in Educational Leadership"
    college: "College of Education, Kinesiology & Social Work"
  - term: "Economics, Agriculture, and Social Sciences"
    college: "College of the Arts, Humanities and Social Sciences"
  - term: "English"
    college: "College of the Arts, Humanities and Social Sciences"
  - term: "History"
    college: "College of the Arts, Humanities and Social Sciences"
  - term: "Interdisciplinary Studies Program"
    college: "Graduate Studies"
  - term: "Kinesiology & Public Health Promotion"
    college: "College of Education, Kinesiology & Social Work"
  - term: "Liberal Studies"
    college: "College of Education, Kinesiology & Social Work"
  - term: "Management Information Systems"
    college: "College of Business Administration"
  - term: "Management, Operations, and Marketing"
    college: "College of Business Administration"
  - term: "Master of Business Administration"
    college: "College of Business Administration"
  - term: "Mathematics"
    college: "College of Science"
  - term: "Music"
    college: "College of the Arts, Humanities and Social Sciences"
  - term: "Other Academic Units"
    college: "Other Academic Units"
  - term: "Philosophy and Modern Languages"
    college: "College of the Arts, Humanities and Social Sciences"
  - term: "Physics, Physical Sciences, and Geology"
    college: "College of Science"
  - term: "Political Science and Public Administration"
    college: "College of the Arts, Humanities and Social Sciences"
  - term: "Psychology and Child Development"
    college: "College of Science"
  - term: "School of Nursing"
    college: "College of Science"
  - term: "Social Work"
    college: "College of Education, Kinesiology & Social Work"
  - term: "Sociology, Gerontology, and Gender Studies"
    college: "College of the Arts, Humanities and Social Sciences"
  - term: "Theatre"
    college: "College of the Arts, Humanities and Social Sciences"
  - term: "University Extended Education"
    college: "Other Academic Units"
  - term: "University Library"
    college: "University Library"
