terms:
  - term: "Academic Affairs"
    college: "Administration"
  - term: "Administration and Finance"
    college: "Administration"
  - term: "Advising and Student Success Center"
    college: "Administration"
  - term: "Brand Values Research Center"
    college: "Administration"
  - term: "California Desert Studies Consortium"
    college: "College of Natural Sciences and Mathematics"
  - term: "Catalyst Center"
    college: "College of Natural Sciences and Mathematics"
  - term: "Center for Applied Biotechnology Studies (CABS)"
    college: "College of Natural Sciences and Mathematics"
  - term: "Center for Autism"
    college: "College of Health and Human Development"
  - term: "Center for Autism: Applied Developmental Core"
    college: "College of Health and Human Development"
  - term: "Center for Boys and Men"
    college: "College of Health and Human Development"
  - term: "Center for Cancer Disparities Research"
    college: "College of Health and Human Development"
  - term: "Center for Careers in Teaching"
    college: "College of Education"
  - term: "Center for Children Who Stutter"
    college: "College of Health and Human Development"
  - term: "Center for Collaborative Research and Prototype Development (CCRPD)"
    college: "College of Engineering and Computer Science"
  - term: "Center for Community Collaboration"
    college: "College of Health and Human Development"
  - term: "Center for Computational and Applied Mathematics (CCAM)"
    college: "College of Engineering and Computer Science"
  - term: "Center for Corporate Reporting and Governance"
    college: "College of Business and Economics"
  - term: "Center for Demographic Research (CDR)"
    college: "Auxiliary Services Corporation"
  - term: "Center for Economic Education"
    college: "College of Business and Economics"
  - term: "Center for Entertainment and Hospitality Management"
    college: "College of Business and Economics"
  - term: "Center for Entertainment and Tourism Communications"
    college: "College of Communications"
  - term: "Center for Entrepreneurship"
    college: "College of Business and Economics"
  - term: "Center for Family Business"
    college: "College of Business and Economics"
  - term: "Center for Healthy Neighborhoods"
    college: "College of Health and Human Development"
  - term: "Center for Information Technology and Business Analytics"
    college: "College of Business and Economics"
  - term: "Center for Insurance Studies"
    college: "College of Business and Economics"
  - term: "Center for Leadership"
    college: "College of Business and Economics"
  - term: "Center for Maximizing Teacher Impact (CMTI)"
    college: "College of Education"
  - term: "Center for Nursing Workforce Excellence"
    college: "College of Health and Human Development"
  - term: "Center for Oral and Public History (COPH)"
    college: "College of Humanities and Social Sciences"
  - term: "Center for Public Policy (CPP)"
    college: "College of Humanities and Social Sciences"
  - term: "Center for Research on Educational Access and Leadership (C-REAL)"
    college: "College of Education"
  - term: "Center for Sociocultural Sport and Olympic Research"
    college: "College of Health and Human Development"
  - term: "Center for Sport Performance"
    college: "College of Health and Human Development"
  - term: "Center for Successful Aging"
    college: "College of Health and Human Development"
  - term: "Center for Sustainability"
    college: "College of Humanities and Social Sciences"
  - term: "Center for the Promotion of Healthy Lifestyles and Obesity Prevention"
    college: "College of Health and Human Development"
  - term: "Daily Titan (Student Newspaper)"
    college: "Student Organizations"
  - term: "Department of Accounting"
    college: "College of Business and Economics"
  - term: "Department of African American Studies"
    college: "College of Humanities and Social Sciences"
  - term: "Department of Aging Studies"
    college: "College of Health and Human Development"
  - term: "Department of American Studies"
    college: "College of Humanities and Social Sciences"
  - term: "Department of Anthropology"
    college: "College of Humanities and Social Sciences"
  - term: "Department of Asian American Studies"
    college: "College of Humanities and Social Sciences"
  - term: "Department of Biological Sciences"
    college: "College of Natural Sciences and Mathematics"
  - term: "Department of Chemistry and Biochemistry"
    college: "College of Natural Sciences and Mathematics"
  - term: "Department of Chicana and Chicano Studies"
    college: "College of Humanities and Social Sciences"
  - term: "Department of Child and Adolescent Studies"
    college: "College of Health and Human Development"
  - term: "Department of Cinema and Television Arts"
    college: "College of Communications"
  - term: "Department of Civil and Environmental Engineering"
    college: "College of Engineering and Computer Science"
  - term: "Department of Communication Sciences and Disorders"
    college: "College of Communications"
  - term: "Department of Communications"
    college: "College of Communications"
  - term: "Department of Computer Science"
    college: "College of Engineering and Computer Science"
  - term: "Department of Counseling"
    college: "College of Health and Human Development"
  - term: "Department of Economics"
    college: "College of Business and Economics"
  - term: "Department of Educational Leadership"
    college: "College of Education"
  - term: "Department of Electrical Engineering"
    college: "College of Engineering and Computer Science"
  - term: "Department of Elementary and Bilingual Education"
    college: "College of Education"
  - term: "Department of English, Comparative Literature, and Linguistics"
    college: "College of Humanities and Social Sciences"
  - term: "Department of Environmental Studies"
    college: "College of Humanities and Social Sciences"
  - term: "Department of Finance"
    college: "College of Business and Economics"
  - term: "Department of Geography and the Environment"
    college: "College of Humanities and Social Sciences"
  - term: "Department of Geological Sciences"
    college: "College of Natural Sciences and Mathematics"
  - term: "Department of History"
    college: "College of Humanities and Social Sciences"
  - term: "Department of Human Communication Studies"
    college: "College of Communications"
  - term: "Department of Human Services"
    college: "College of Health and Human Development"
  - term: "Department of Information Systems & Decision Sciences"
    college: "College of Engineering and Computer Science"
  - term: "Department of Kinesiology"
    college: "College of Health and Human Development"
  - term: "Department of Latin American Studies"
    college: "College of Humanities and Social Sciences"
  - term: "Department of Liberal Studies"
    college: "College of Humanities and Social Sciences"
  - term: "Department of Literacy Reading Education"
    college: "College of Education"
  - term: "Department of Management"
    college: "College of Business and Economics"
  - term: "Department of Marketing / Business Communications"
    college: "College of Business and Economics"
  - term: "Department of Mathematics"
    college: "College of Natural Sciences and Mathematics"
  - term: "Department of Mechanical Engineering"
    college: "College of Engineering and Computer Science"
  - term: "Department of Modern Languages and Literatures"
    college: "College of Humanities and Social Sciences"
  - term: "Department of Philosophy"
    college: "College of Humanities and Social Sciences"
  - term: "Department of Physics"
    college: "College of Natural Sciences and Mathematics"
  - term: "Department of Politics, Administration, and Justice"
    college: "College of Humanities and Social Sciences"
  - term: "Department of Psychology"
    college: "College of Humanities and Social Sciences"
  - term: "Department of Public Health"
    college: "College of Health and Human Development"
  - term: "Department of Religious Studies"
    college: "College of Humanities and Social Sciences"
  - term: "Department of Secondary Education"
    college: "College of Education"
  - term: "Department of Social Work"
    college: "College of Health and Human Development"
  - term: "Department of Sociology"
    college: "College of Humanities and Social Sciences"
  - term: "Department of Special Education"
    college: "College of Education"
  - term: "Department of Theatre and Dance"
    college: "College of the Arts"
  - term: "Department of Visual Arts"
    college: "College of the Arts"
  - term: "Department of Women and Gender Studies"
    college: "College of Humanities and Social Sciences"
  - term: "ECS Center for Cybersecurity"
    college: "College of Engineering and Computer Science"
  - term: "Fibromyalgia and Chronic Pain Center"
    college: "College of Health and Human Development"
  - term: "Gianneschi Center for Nonprofit Research"
    college: "College of Business and Economics"
  - term: "Grand Central Art Center"
    college: "College of the Arts"
  - term: "Gravitational Wave Physics and Astronomy Center (GWPAC)"
    college: "College of Natural Sciences and Mathematics"
  - term: "Hazel Miller Croy Reading Center"
    college: "College of Education"
  - term: "Health Promotion Research Institute"
    college: "College of Health and Human Development"
  - term: "Honors Program"
    college: "Honors Program"
  - term: "Human Resources, Diversity and Inclusion"
    college: "Administration"
  - term: "Information Technology"
    college: "College of Engineering and Computer Science"
  - term: "Maxwell Center for International Communications"
    college: "College of Communications"
  - term: "Nicholas and Lee Begovich Gallery"
    college: "College of the Arts"
  - term: "Office of the President"
    college: "Administration"
  - term: "Pollak Library"
    college: "Pollak Library"
  - term: "Real Estate and Land Use Institute"
    college: "College of Business and Economics"
  - term: "School of Music"
    college: "College of the Arts"
  - term: "School of Nursing"
    college: "College of Health and Human Development"
  - term: "Schools First FCU Center for Creativity and Critical Thinking"
    college: "College of Education"
  - term: "Small Business Development Center"
    college: "College of Business and Economics"
  - term: "Small Business Institute"
    college: "College of Business and Economics"
  - term: "Social Science Research Center"
    college: "College of Humanities and Social Sciences"
  - term: "South Central Coastal Information Center"
    college: "College of Humanities and Social Sciences"
  - term: "Student Affairs"
    college: "Administration"
  - term: "The Sales Leadership Center"
    college: "College of Business and Economics"
  - term: "University Advancement"
    college: "Administration"
  - term: "Woods Center for Economic Analysis and Forecasting"
    college: "College of Business and Economics"
