terms:
  - term: "Accountancy"
  - term: "Administration, Rehabilitation, and Postsecondary Education"
  - term: "Aerospace Engineering"
  - term: "Aerospace Studies"
  - term: "Africana Studies"
  - term: "American Indian Studies"
  - term: "Anthropology"
  - term: "Arts and Design"
  - term: "Arts and Sciences"
  - term: "Astronomy"
  - term: "Biology"
  - term: "Chemistry and Biochemistry"
  - term: "Chicana and Chicano Studies"
  - term: "Child and Family Development"
  - term: "Civil, Construction, and Environmental Engineering"
  - term: "Classics and Humanities"
  - term: "Communication"
  - term: "Computer Science"
  - term: "Counseling and School Psychology"
  - term: "Dual Language and English Learner Education"
  - term: "Economics"
  - term: "Education"
  - term: "Electrical and Computer Engineering"
  - term: "English and Comparative Literature"
  - term: "European Studies"
  - term: "Exercise and Nutritional Sciences"
  - term: "Finance"
  - term: "General Studies"
  - term: "Geography"
  - term: "Geological Sciences"
  - term: "History"
  - term: "Hospitality and Tourism Management"
  - term: "Interdisciplinary Studies"
  - term: "Joint Ph.D. Program with Claremont Graduate University"
  - term: "Journalism and Media Studies"
  - term: "Linguistics and Asian/Middle Eastern Languages"
  - term: "Management"
  - term: "Management Information Systems"
  - term: "Marketing"
  - term: "Mathematics and Statistics"
  - term: "Mechanical Engineering"
  - term: "Military Science"
  - term: "Music and Dance"
  - term: "Naval Science"
  - term: "Nursing"
  - term: "Philosophy"
  - term: "Physics"
  - term: "Political Science"
  - term: "Professional Studies"
  - term: "Psychology"
  - term: "Public Affairs"
  - term: "Public Health"
  - term: "Religious Studies"
  - term: "Rhetoric and Writing Studies"
  - term: "School of Teacher Education"
  - term: "Social Work"
  - term: "Sociology"
  - term: "Spanish and Portuguese Languages and Literatures"
  - term: "Special Education"
  - term: "Speech, Language, and Hearing Sciences"
  - term: "Theatre, Television, and Film"
  - term: "Weber Honors College"
  - term: "Women's Studies"
