terms:
  - term: "Accounting and Finance"
    college: "Business and Public Administration"
  - term: "Advanced Educational Studies"
    college: "Social Sciences and Education"
  - term: "Anthropology"
    college: "Social Sciences and Education"
  - term: "Art and Art History"
    college: "Arts and Humanities"
  - term: "Biology"
    college: "Natural Sciences, Mathematics, and Engineering"
  - term: "Business Administration"
    college: "Business and Public Administration"
  - term: "Chemistry and Biochemistry"
    college: "Natural Sciences, Mathematics, and Engineering"
  - term: "Child, Adolescent, and Family Studies"
    college: "Social Sciences and Education"
  - term: "Communications"
    college: "Arts and Humanities"
  - term: "Computer and Electrical Engineering and Computer Science"
    college: "Natural Sciences, Mathematics, and Engineering"
  - term: "Criminal Justice"
    college: "Social Sciences and Education"
  - term: "Economics"
    college: "Business and Public Administration"
  - term: "Educational Leadership (DPEL)"
    college: "Social Sciences and Education"
  - term: "English"
    college: "Arts and Humanities"
  - term: "Geological Sciences"
    college: "Natural Sciences, Mathematics, and Engineering"
  - term: "History"
    college: "Arts and Humanities"
  - term: "Interdisciplinary Programs"
    college: "Arts and Humanities"
  - term: "Kinesiology"
    college: "Social Sciences and Education"
  - term: "Liberal Studies"
    college: "Social Sciences and Education"
  - term: "Management and Marketing"
    college: "Business and Public Administration"
  - term: "Mathematics"
    college: "Natural Sciences, Mathematics, and Engineering"
  - term: "Modern Languages and Literatures"
    college: "Arts and Humanities"
  - term: "Music"
    college: "Arts and Humanities"
  - term: "Nursing"
    college: "Natural Sciences, Mathematics, and Engineering"
  - term: "Philosophy and Religious Studies"
    college: "Arts and Humanities"
  - term: "Physics and Engineering"
    college: "Natural Sciences, Mathematics, and Engineering"
  - term: "Political Science"
    college: "Social Sciences and Education"
  - term: "Psychology"
    college: "Social Sciences and Education"
  - term: "Public Policy and Administration"
    college: "Business and Public Administration"
  - term: "Social Work"
    college: "Social Sciences and Education"
  - term: "Sociology"
    college: "Social Sciences and Education"
  - term: "Teacher Education"
    college: "Social Sciences and Education"
  - term: "Theatre"
    college: "Arts and Humanities"
