terms:
  - term: "Anthropology"
  - term: "Applied Physics"
  - term: "Art"
  - term: "Biology"
  - term: "Business"
  - term: "Chemistry"
  - term: "Chicana/o Studies"
  - term: "Communication"
  - term: "Computer Science & Information Technology"
  - term: "Early Childhood Studies"
  - term: "Economics"
  - term: "Education"
  - term: "English"
  - term: "Environmental Science & Resource Management"
  - term: "Global Studies"
  - term: "Health Science"
  - term: "History"
  - term: "Liberal Studies"
  - term: "Mathematics"
  - term: "Mechatronics Engineering"
  - term: "Nursing"
  - term: "Performing Arts"
  - term: "Political Science"
  - term: "Psychology"
  - term: "Sociology"
  - term: "Spanish"
