terms:
  - term: "Accounting and Finance"
    college: "College of Business and Economics"
  - term: "Anthropology, Geography and Environmental Studies"
    college: "College of Letters, Arts, and Social Sciences"
  - term: "Art"
    college: "College of Letters, Arts, and Social Sciences"
  - term: "Biological Sciences"
    college: "College of Science"
  - term: "Business Administration"
    college: "Business Administration"
  - term: "Chemistry and Biochemistry"
    college: "College of Science"
  - term: "Communication"
    college: "College of Letters, Arts, and Social Sciences"
  - term: "Computer Science"
    college: "College of Science"
  - term: "Criminal Justice"
    college: "College of Letters, Arts, and Social Sciences"
  - term: "Earth and Environmental Sciences"
    college: "College of Science"
  - term: "Economics"
    college: "College of Business and Economics"
  - term: "Educational Leadership"
    college: "College of Education and Allied Studies"
  - term: "Educational Psychology"
    college: "College of Education and Allied Studies"
  - term: "Engineering"
    college: "College of Science"
  - term: "English"
    college: "College of Letters, Arts, and Social Sciences"
  - term: "Ethnic Studies"
    college: "College of Letters, Arts, and Social Sciences"
  - term: "Global Studies"
    college: "College of Letters, Arts, and Social Sciences"
  - term: "History"
    college: "College of Letters, Arts, and Social Sciences"
  - term: "Hospitality, Recreation and Tourism"
    college: "College of Education and Allied Studies"
  - term: "Human Development and Women's Studies"
    college: "College of Letters, Arts, and Social Sciences"
  - term: "Information Studies"
    college: "University Libraries"
  - term: "Kinesiology"
    college: "College of Education and Allied Studies"
  - term: "Liberal Studies"
    college: "College of Letters, Arts, and Social Sciences"
  - term: "Management"
    college: "College of Business and Economics"
  - term: "Marketing"
    college: "College of Business and Economics"
  - term: "Mathematics"
    college: "College of Science"
  - term: "Modern Languages and Literatures"
    college: "College of Letters, Arts, and Social Sciences"
  - term: "Music"
    college: "College of Letters, Arts, and Social Sciences"
  - term: "Nursing"
    college: "College of Science"
  - term: "Online Teaching and Learning"
    college: "College of Education and Allied Studies"
  - term: "Philosophy and Religious Studies"
    college: "College of Letters, Arts, and Social Sciences"
  - term: "Physics"
    college: "College of Science"
  - term: "Political Science"
    college: "College of Letters, Arts, and Social Sciences"
  - term: "Psychology"
    college: "College of Science"
  - term: "Public Affairs and Administration"
    college: "College of Letters, Arts, and Social Sciences"
  - term: "Public Health"
    college: "College of Science"
  - term: "Social Work"
    college: "College of Letters, Arts, and Social Sciences"
  - term: "Sociology"
    college: "College of Letters, Arts, and Social Sciences"
  - term: "Speech, Language, and Hearing Sciences"
    college: "College of Letters, Arts, and Social Sciences"
  - term: "Statistics and Biostatistics"
    college: "College of Science"
  - term: "Teacher Education"
    college: "College of Education and Allied Studies"
  - term: "Theatre and Dance"
    college: "College of Letters, Arts, and Social Sciences"
