terms:
  - term: "Accountancy"
  - term: "Advanced Studies in Education and Counseling"
  - term: "Africana Studies"
  - term: "American Indian Studies"
  - term: "American Studies"
  - term: "Anthropology"
  - term: "Art"
  - term: "Asian and Asian American Studies"
  - term: "Asian Languages"
  - term: "Athletics"
  - term: "Biological Sciences"
  - term: "Biomedical Engineering"
  - term: "Chemical Engineering"
  - term: "Chemistry and Biochemistry"
  - term: "Chicano and Latino Studies"
  - term: "Child Development and Family Studies"
  - term: "Chinese Studies"
  - term: "Civil Engineering and Construction Engineering Management"
  - term: "Classics"
  - term: "Communication Studies"
  - term: "Comparative World Literature"
  - term: "Computer Engineering and Computer Science"
  - term: "Consumer Affairs"
  - term: "Counseling and Psychological Services"
  - term: "Criminology and Criminal Justice"
  - term: "Dance"
  - term: "Design"
  - term: "Economics"
  - term: "Educational Leadership"
  - term: "Electrical Engineering"
  - term: "Emergency Management"
  - term: "Engineering Technology"
  - term: "English"
  - term: "Environmental Science and Public Policy"
  - term: "Family and Consumer Sciences"
  - term: "Fashion Merchandising and Design"
  - term: "Film and Electronic Arts"
  - term: "Finance"
  - term: "Food Science"
  - term: "French"
  - term: "Geography"
  - term: "Geological Sciences"
  - term: "German"
  - term: "Gerontology"
  - term: "Global Migration Studies"
  - term: "Health Care Administration"
  - term: "Health Science"
  - term: "History"
  - term: "Hospitality Management"
  - term: "Human Development"
  - term: "Information Systems"
  - term: "International Business"
  - term: "International Studies"
  - term: "Italian"
  - term: "Japanese"
  - term: "Jewish Studies"
  - term: "Journalism and Public Relations"
  - term: "Kinesiology"
  - term: "Latin American Studies"
  - term: "Legal Studies"
  - term: "Liberal Studies"
  - term: "Linguistics"
  - term: "Management and Human Resources Management"
  - term: "Marketing"
  - term: "Mathematics and Statistics"
  - term: "Mechanical and Aerospace Engineering"
  - term: "Medieval and Renaissance Studies"
  - term: "Military Science"
  - term: "Music"
  - term: "Nursing"
  - term: "Nutrition and Dietetics"
  - term: "Ocean Studies Institute"
  - term: "Peace Studies"
  - term: "Philosophy"
  - term: "Physical Therapy"
  - term: "Physics and Astronomy"
  - term: "Political Science"
  - term: "Psychology"
  - term: "Public Policy and Administration"
  - term: "Recreation and Leisure Studies"
  - term: "Religious Studies"
  - term: "Romance, German, Russian Languages and Literatures"
  - term: "Russian"
  - term: "Science Education"
  - term: "Single Subject Teacher Education Program"
  - term: "Social Work"
  - term: "Sociology"
  - term: "Spanish"
  - term: "Speech-Language Pathology"
  - term: "Student Leadership and Recreation"
  - term: "Teacher Education"
  - term: "Theatre Arts"
  - term: "Translation Studies"
  - term: "University Honors Program"
  - term: "University Library"
  - term: "Women's, Gender, and Sexuality Studies"