terms:
  - term: "Anthropology"
    college: "Arts and Sciences"
  - term: "Applied Physics"
    college: "Arts and Sciences"
  - term: "Art"
    college: "Arts and Sciences"
  - term: "Biology"
    college: "Arts and Sciences"
  - term: "Business"
    college: "Business"
  - term: "Chemistry"
    college: "Arts and Sciences"
  - term: "Chicana/o Studies"
    college: "Arts and Sciences"
  - term: "Communication"
    college: "Arts and Sciences"
  - term: "Computer Science & Information Technology"
    college: "Arts and Sciences"
  - term: "Early Childhood Studies"
    college: "Education"
  - term: "Economics"
    college: "Education"
  - term: "Education"
    college: "Education"
  - term: "English"
    college: "Arts and Sciences"
  - term: "Environmental Science & Resource Management"
    college: "Arts and Sciences"
  - term: "Extended University"
    college: "Extended University"
  - term: "Global Studies"
    college: "Arts and Sciences"
  - term: "Health Science"
    college: "Arts and Sciences"
  - term: "History"
    college: "Arts and Sciences"
  - term: "Liberal Studies"
    college: "Education"
  - term: "Library"
    college: "Library"
  - term: "Mathematics"
    college: "Arts and Sciences"
  - term: "Mechatronics Engineering"
    college: "Arts and Sciences"
  - term: "Nursing"
    college: "Nursing"
  - term: "Performing Arts"
    college: "Arts and Sciences"
  - term: "Political Science"
    college: "Arts and Sciences"
  - term: "Psychology"
    college: "Arts and Sciences"
  - term: "Santa Rosa Island Research Station"
    college: "Santa Rosa Island Research Station"
  - term: "Sociology"
    college: "Arts and Sciences"
  - term: "Spanish"
    college: "Arts and Sciences"
