terms:
  - term: "Academic Policies & Planning Committee"
    college: "Academic Offices"
  - term: "Academic Resources"
    college: "Academic Offices"
  - term: "Academic Senate Meetings"
    college: "Academic Offices"
  - term: "Accountancy"
    college: "Craig School of Business"
  - term: "Administrative Division"
    college: "Academic Offices"
  - term: "Administrative Operations and Organizational Excellence"
    college: "Academic Offices"
  - term: "Advancement Services"
    college: "Administrative Services"
  - term: "Aerospace Studies"
    college: "Craig School of Business"
  - term: "Africana Studies"
    college: "Social Sciences"
  - term: "Agricultural Business"
    college: "Jordan College of Agricultural Sciences and Technology"
  - term: "Alumni Relations"
    college: "Alumni Association"
  - term: "Animal Sciences and Agricultural Education"
    college: "Jordan College of Agricultural Sciences and Technology"
  - term: "Anthropology"
    college: "Social Sciences"
  - term: "Armenian Studies Program"
    college: "Arts and Humanities"
  - term: "Art and Design"
    college: "Arts and Humanities"
  - term: "Auxiliary Operations & Enterprise Development"
    college: "Auxiliary Services"
  - term: "Biology"
    college: "Science and Mathematics"
  - term: "Business Teacher Education Program"
    college: "Craig School of Business"
  - term: "Chemistry and Biochemistry"
    college: "Science and Mathematics"
  - term: "Chicano and Latin American Studies"
    college: "Social Sciences"
  - term: "Child, Family and Consumer Sciences"
    college: "Social Sciences"
  - term: "Civil and Geomatics Engineering"
    college: "Lyles College of Engineering"
  - term: "Communication"
    college: "Arts and Humanities"
  - term: "Communicative Sciences and Deaf Studies"
    college: "Health and Human Services"
  - term: "Community & Economic Development (OCED)"
    college: "Academic Affairs"
  - term: "Computer Science"
    college: "Science and Mathematics"
  - term: "Construction Management"
    college: "Lyles College of Engineering"
  - term: "Continuing & Global Education"
    college: "Academic Affairs"
  - term: "Counselor Education and Rehabilitation"
    college: "Kremen School of Education and Human Development"
  - term: "Criminology"
    college: "Social Sciences"
  - term: "Curriculum and Instruction"
    college: "Kremen School of Education and Human Development"
  - term: "Digital Services Division"
    college: "Henry Madden Library"
  - term: "DISCOVERe Hub"
    college: "Academic Affairs"
  - term: "Doctoral Program in Educational Leadership"
    college: "Academic Affairs"
  - term: "Earth and Environmental Sciences"
    college: "Science and Mathematics"
  - term: "Economics"
    college: "Craig School of Business"
  - term: "Education"
    college: "Kremen School of Education and Human Development"
  - term: "Educational Leadership"
    college: "Academic Affairs"
  - term: "Electrical and Computer Engineering"
    college: "Lyles College of Engineering"
  - term: "English"
    college: "Arts and Humanities"
  - term: "Enrollment Management"
    college: "Academic Affairs"
  - term: "Executive Committee"
    college: "Academic Offices"
  - term: "FACEL"
    college: "Academic Offices"
  - term: "Facilities Management"
    college: "Academic Affairs"
  - term: "Faculty Affairs"
    college: "Academic Affairs"
  - term: "Faculty Equity & Diversity"
    college: "Academic Offices"
  - term: "Finance and Business Law"
    college: "Craig School of Business"
  - term: "Fine Arts"
    college: "Arts and Humanities"
  - term: "Food Science and Nutrition"
    college: "Jordan College of Agricultural Sciences and Technology"
  - term: "General Education Committee"
    college: "Academic Offices"
  - term: "Geography and City and Regional Planning"
    college: "Social Sciences"
  - term: "Gerontology"
    college: "Health and Human Services"
  - term: "Graduate Business Programs"
    college: "Craig School of Business"
  - term: "Graduate Studies"
    college: "Academic Affairs"
  - term: "History"
    college: "Social Sciences"
  - term: "Human Resources"
    college: "Administration and Finance"
  - term: "Humanities"
    college: "Arts and Humanities"
  - term: "Industrial Arts"
    college: "Jordan College of Agricultural Sciences and Technology"
  - term: "Industrial Technology"
    college: "Jordan College of Agricultural Sciences and Technology"
  - term: "Information Systems and Decision Sciences"
    college: "Craig School of Business"
  - term: "Institutional Effectiveness"
    college: "Academic Affairs"
  - term: "Intellectual Property Review Committee"
    college: "Academic Offices"
  - term: "International Student Support Programs"
    college: "Continuing and Global Education"
  - term: "Kinesiology"
    college: "Health and Human Services"
  - term: "Liberal Studies"
    college: "Kremen School of Education and Human Development"
  - term: "Life Science"
    college: "Science and Mathematics"
  - term: "Linguistics"
    college: "Arts and Humanities"
  - term: "Literacy, Early, Bilingual, and Special Education"
    college: "Kremen School of Education and Human Development"
  - term: "Lyles Center for Innovation & Enterpreneurship"
    college: "Academic Affairs"
  - term: "Maddy Institute"
    college: "Academic Affairs"
  - term: "Management"
    college: "Craig School of Business"
  - term: "Marketing and Logistics"
    college: "Craig School of Business"
  - term: "Mathematics"
    college: "Science and Mathematics"
  - term: "Mechanical Engineering"
    college: "Lyles College of Engineering"
  - term: "Media, Communications and Journalism"
    college: "Arts and Humanities"
  - term: "Military Science (Army ROTC)"
    college: "Craig School of Business"
  - term: "Modern and Classical Languages and Literatures"
    college: "Arts and Humanities"
  - term: "Music"
    college: "Arts and Humanities"
  - term: "Nominating / Elections Committee"
    college: "Academic Offices"
  - term: "Nursing"
    college: "Health and Human Services"
  - term: "Office of Institutional Effectiveness (OIE)"
    college: "Academic Affairs"
  - term: "Personnel Committee"
    college: "Academic Offices"
  - term: "Philosophy"
    college: "Arts and Humanities"
  - term: "Physical Education"
    college: "Health and Human Services"
  - term: "Physical Therapy"
    college: "Health and Human Services"
  - term: "Physics"
    college: "Science and Mathematics"
  - term: "Plant Science"
    college: "Jordan College of Agricultural Sciences and Technology"
  - term: "Political Science"
    college: "Social Sciences"
  - term: "Psychology"
    college: "Science and Mathematics"
  - term: "Public Health"
    college: "Health and Human Services"
  - term: "Public Safety/University Police Department"
    college: "Administration and Finance"
  - term: "Public Services Division"
    college: "Academic Offices"
  - term: "Recreation Administration"
    college: "Health and Human Services"
  - term: "Research & Sponsored Programs"
    college: "Academic Affairs"
  - term: "Research Awards Review Committee"
    college: "Academic Offices"
  - term: "Richter Center For Community Engagement & Service-Learning"
    college: "Academic Affairs"
  - term: "School of Nursing"
    college: "Health and Human Services"
  - term: "Social Science"
    college: "Social Sciences"
  - term: "Social Work Education"
    college: "Health and Human Services"
  - term: "Sociology"
    college: "Social Sciences"
  - term: "Special Collections Research Centers Division"
    college: "Henry Madden Library"
  - term: "Speech Arts"
    college: "Arts and Humanities"
  - term: "Student Affairs"
    college: "Academic Affairs"
  - term: "Student Affairs"
    college: "Academic Offices"
  - term: "Student Affairs Administration"
    college: "Academic Affairs"
  - term: "Student Health and Wellness Services"
    college: "Academic Affairs"
  - term: "Student Success Services"
    college: "Academic Affairs"
  - term: "Technology Innovations For Learning And Teaching And Center For The Scholarly Advancement Of Learning And Teaching (TILT/CSALT)"
    college: "Academic Affairs"
  - term: "Theatre and Dance"
    college: "Arts and Humanities"
  - term: "Undergraduate Studies"
    college: "Academic Affairs"
  - term: "University Communications"
    college: "Arts and Humanities"
  - term: "University Initiatives"
    college: "Academic Affairs"
  - term: "Vice Provost"
    college: "Academic Affairs"
  - term: "Viticulture and Enology"
    college: "Jordan College of Agricultural Sciences and Technology"
  - term: "Women's, Gender, and Sexuality Studies"
    college: "Social Sciences"
