terms:
  - term: "Accountancy"
    college: "Business"
  - term: "Anthropology"
    college: "Liberal & Creative Arts"
  - term: "Art"
    college: "Liberal & Creative Arts"
  - term: "Art History"
    college: "Liberal & Creative Arts"
  - term: "Asian American Studies"
    college: "Ethnic Studies"
  - term: "Astronomy and Astrophysics"
    college: "Science & Engineering"
  - term: "Biology"
    college: "Science & Engineering"
  - term: "Biology: Concentration in Cell and Molecular Biology"
    college: "Science & Engineering"
  - term: "Biology: Concentration in Integrative Biology"
    college: "Science & Engineering"
  - term: "Biology: Concentration in Physiology and Behavioral Biology"
    college: "Science & Engineering"
  - term: "Biomedical Science: Concentration in Biotechnology"
    college: "Science & Engineering"
  - term: "Biomedical Science: Concentration in Stem Cell Science"
    college: "Science & Engineering"
  - term: "Broadcast and Electronic Communication Arts"
    college: "Liberal & Creative Arts"
  - term: "Business Administration"
    college: "Business"
  - term: "Business Analytics"
    college: "Business"
  - term: "Chemistry"
    college: "Science & Engineering"
  - term: "Chemistry: Concentration in Biochemistry"
    college: "Science & Engineering"
  - term: "Chinese"
    college: "Liberal & Creative Arts"
  - term: "Cinema"
    college: "Liberal & Creative Arts"
  - term: "Cinema Studies"
    college: "Liberal & Creative Arts"
  - term: "Civil Engineering"
    college: "Science & Engineering"
  - term: "Classics"
    college: "Liberal & Creative Arts"
  - term: "Clinical Laboratory Science"
    college: "Health & Social Sciences"
  - term: "Clinical Mental Health Counseling"
    college: "Health & Social Sciences"
  - term: "Communication Studies"
    college: "Liberal & Creative Arts"
  - term: "Communicative Disorders"
    college: "Education"
  - term: "Comparative Literature"
    college: "Liberal & Creative Arts"
  - term: "Computer Science"
    college: "Science & Engineering"
  - term: "Counseling"
    college: "Health & Social Sciences"
  - term: "Counseling: Concentration in Marriage, Family, and Child Counseling"
    college: "Health & Social Sciences"
  - term: "Creative Writing"
    college: "Liberal & Creative Arts"
  - term: "Curriculum and Instruction"
    college: "Education"
  - term: "Data Science and Artificial Intelligence"
    college: "Science & Engineering"
  - term: "Design"
    college: "Liberal & Creative Arts"
  - term: "Early Childhood Education"
    college: "Education"
  - term: "Economics"
    college: "Business"
  - term: "Education"
    college: "Education"
  - term: "Education: Concentration in Adult Education"
    college: "Education"
  - term: "Education: Concentration in Educational Administration"
    college: "Education"
  - term: "Education: Concentration in Elementary Education"
    college: "Education"
  - term: "Education: Concentration in Equity and Social Justice in Education"
    college: "Education"
  - term: "Education: Concentration in Instructional Technologies"
    college: "Education"
  - term: "Education: Concentration in Language and Literacy Education"
    college: "Education"
  - term: "Education: Concentration in Mathematics Education"
    college: "Education"
  - term: "Education: Concentration in Secondary Education"
    college: "Education"
  - term: "Education: Concentration in Special Education"
    college: "Education"
  - term: "Education: Concentration in Special Interest Area"
    college: "Education"
  - term: "Educational Leadership"
    college: "Education"
  - term: "Electrical and Computer Engineering"
    college: "Science & Engineering"
  - term: "Engineering"
    college: "Science & Engineering"
  - term: "Engineering: Concentration in Embedded Electrical and Computer Systems"
    college: "Science & Engineering"
  - term: "Engineering: Concentration in Energy Systems"
    college: "Science & Engineering"
  - term: "Engineering: Concentration in Structural/Earthquakes"
    college: "Science & Engineering"
  - term: "English Literatures"
    college: "Liberal & Creative Arts"
  - term: "English: Concentration in Composition"
    college: "Liberal & Creative Arts"
  - term: "English: Concentration in Linguistics"
    college: "Liberal & Creative Arts"
  - term: "English: Concentration in Teaching English to Speakers of Other Languages"
    college: "Liberal & Creative Arts"
  - term: "Ethnic Studies"
    college: "Ethnic Studies"
  - term: "Ethnic Studies: American Indian Studies"
    college: "Ethnic Studies"
  - term: "Family and Consumer Sciences"
    college: "Health & Social Sciences"
  - term: "French"
    college: "Liberal & Creative Arts"
  - term: "Geographic Information Science"
    college: "Science & Engineering"
  - term: "Geography"
    college: "Science & Engineering"
  - term: "Geography: Concentration in Resource Management and Environmental Planning"
    college: "Science & Engineering"
  - term: "Geosciences"
    college: "Science & Engineering"
  - term: "German"
    college: "Liberal & Creative Arts"
  - term: "Gerontology"
    college: "Health & Social Sciences"
  - term: "History"
    college: "Liberal & Creative Arts"
  - term: "Human Sexuality Studies"
    college: "Health & Social Sciences"
  - term: "Humanities"
    college: "Liberal & Creative Arts"
  - term: "Industrial Organizational Psychology"
    college: "Science & Engineering"
  - term: "Interdisciplinary Marine and Estuarine Sciences"
    college: "Science & Engineering"
  - term: "Interdisciplinary Studies"
  - term: "International Relations"
    college: "Liberal & Creative Arts"
  - term: "Italian"
    college: "Liberal & Creative Arts"
  - term: "Japanese"
    college: "Liberal & Creative Arts"
  - term: "Kinesiology"
    college: "Health & Social Sciences"
  - term: "Mathematics"
    college: "Science & Engineering"
  - term: "Mechanical Engineering"
    college: "Science & Engineering"
  - term: "Museum Studies"
    college: "Liberal & Creative Arts"
  - term: "Music"
    college: "Liberal & Creative Arts"
  - term: "Nursing"
    college: "Health & Social Sciences"
  - term: "Nursing: Concentration in Family Nurse Practitioner"
    college: "Health & Social Sciences"
  - term: "Philosophy"
    college: "Liberal & Creative Arts"
  - term: "Physics"
    college: "Science & Engineering"
  - term: "Political Science"
    college: "Liberal & Creative Arts"
  - term: "Psychological Science: Concentration in Developmental Psychology"
    college: "Science & Engineering"
  - term: "Psychological Science: Concentration in Mind, Brain & Behavior"
    college: "Science & Engineering"
  - term: "Psychological Science: Concentration in Social, Personality, and Affective Science"
    college: "Science & Engineering"
  - term: "Psychology"
    college: "Science & Engineering"
  - term: "Psychology: Concentration in Clinical Psychology"
    college: "Science & Engineering"
  - term: "Psychology: Concentration in School Psychology"
    college: "Science & Engineering"
  - term: "Public Administration"
    college: "Health & Social Sciences"
  - term: "Public Health"
    college: "Health & Social Sciences"
  - term: "Quantitative Economics"
    college: "Business"
  - term: "Recreation, Parks & Tourism"
    college: "Health & Social Sciences"
  - term: "Social Work"
    college: "Health & Social Sciences"
  - term: "Spanish"
    college: "Liberal & Creative Arts"
  - term: "Special Education"
    college: "Education"
  - term: "Speech, Language, and Hearing Sciences"
    college: "Education"
  - term: "Statistical Data Science"
    college: "Science & Engineering"
  - term: "Theatre Arts"
    college: "Liberal & Creative Arts"
  - term: "Theatre Arts: Concentration in Design/Technical Production"
    college: "Liberal & Creative Arts"
  - term: "Women & Gender Studies"
    college: "Liberal & Creative Arts"
