terms:
  - term: "Department of Biology"
    college: "College of Natural and Behavioral Sciences"
  - term: "Department of Computer Science"
    college: "College of Natural and Behavioral Sciences"
  - term: "Department of English"
    college: "College of Arts and Humanities"
  - term: "Department of History"
    college: "College of Arts and Humanities"
  - term: "Department of Interdisciplinary Studies"
    college: "College of Arts and Humanities"
  - term: "Department of Philosophy"
    college: "College of Arts and Humanities"
  - term: "Department of Psychology"
    college: "College of Natural and Behavioral Sciences"
  - term: "Department of Social Work"
    college: "College of Health, Human Services and Nursing"
  - term: "Department of Sociology"
    college: "College of Natural and Behavioral Sciences"
  - term: "Division of Graduate Education"
    college: "College of Education"
  - term: "Humanities External Program"
    college: "College of Extended and International Education"
  - term: "Quality Assurance Program"
    college: "College of Extended and International Education"
