terms:
  - term: "Accountancy"
  - term: "Anthropology"
  - term: "Art"
  - term: "Art History"
  - term: "Asian American Studies"
  - term: "Biology"
  - term: "Biology: Concentration in Cell and Molecular Biology"
  - term: "Biology: Concentration in Integrative Biology"
  - term: "Biology: Concentration in Physiology and Behavioral Biology"
  - term: "Biomedical Science: Concentration in Biotechnology"
  - term: "Biomedical Science: Concentration in Stem Cell Science"
  - term: "Broadcast and Electronic Communication Arts"
  - term: "Business Administration"
  - term: "Business Analytics"
  - term: "Chemistry"
  - term: "Chemistry: Concentration in Biochemistry"
  - term: "Chinese"
  - term: "Cinema"
  - term: "Cinema Studies"
  - term: "Classics"
  - term: "Clinical Laboratory Science"
  - term: "Clinical Mental Health Counseling"
  - term: "Communication Studies"
  - term: "Communicative Disorders"
  - term: "Comparative Literature"
  - term: "Computer Science"
  - term: "Counseling"
  - term: "Counseling: Concentration in Marriage, Family, and Child Counseling"
  - term: "Creative Writing"
  - term: "Curriculum and Instruction"
  - term: "Design"
  - term: "Economics"
  - term: "Education"
  - term: "Education: Concentration in Adult Education"
  - term: "Education: Concentration in Early Childhood Education"
  - term: "Education: Concentration in Educational Administration"
  - term: "Education: Concentration in Elementary Education"
  - term: "Education: Concentration in Equity and Social Justice in Education"
  - term: "Education: Concentration in Instructional Technologies"
  - term: "Education: Concentration in Language and Literacy Education"
  - term: "Education: Concentration in Mathematics Education"
  - term: "Education: Concentration in Secondary Education"
  - term: "Education: Concentration in Special Education"
  - term: "Education: Concentration in Special Interest Area"
  - term: "Educational Leadership"
  - term: "Engineering"
  - term: "Engineering: Concentration in Embedded Electrical and Computer Systems"
  - term: "Engineering: Concentration in Energy Systems"
  - term: "Engineering: Concentration in Structural/Earthquakes"
  - term: "English Literatures"
  - term: "English: Concentration in Composition"
  - term: "English: Concentration in Linguistics"
  - term: "English: Concentration in Teaching English to Speakers of Other Languages"
  - term: "Ethnic Studies"
  - term: "Ethnic Studies: American Indian Studies"
  - term: "Family and Consumer Sciences"
  - term: "French"
  - term: "Geographic Information Science"
  - term: "Geography"
  - term: "Geography: Concentration in Resource Management and Environmental Planning"
  - term: "Geosciences"
  - term: "German"
  - term: "Gerontology"
  - term: "History"
  - term: "Human Sexuality Studies"
  - term: "Humanities"
  - term: "Industrial Organizational Psychology"
  - term: "Interdisciplinary Marine and Estuarine Sciences"
  - term: "Interdisciplinary Studies"
  - term: "International Relations"
  - term: "Italian"
  - term: "Japanese"
  - term: "Kinesiology"
  - term: "Marine Science"
  - term: "Mathematics"
  - term: "Museum Studies"
  - term: "Music"
  - term: "Nursing"
  - term: "Nursing: Concentration in Family Nurse Practitioner"
  - term: "Philosophy"
  - term: "Physics"
  - term: "Physics: Concentration in Astronomy"
  - term: "Political Science"
  - term: "Psychology"
  - term: "Psychology: Concentration in Clinical Psychology"
  - term: "Psychology: Concentration in Developmental Psychology"
  - term: "Psychology: Concentration in Mind, Brain & Behavior"
  - term: "Psychology: Concentration in School Psychology"
  - term: "Psychology: Concentration in Social, Personality, and Affective Science"
  - term: "Public Administration"
  - term: "Public Health"
  - term: "Quantitative Economics"
  - term: "Recreation, Parks & Tourism"
  - term: "Social Work"
  - term: "Spanish"
  - term: "Special Education"
  - term: "Speech, Language, and Hearing Sciences"
  - term: "Statistical Data Science"
  - term: "Theatre Arts"
  - term: "Theatre Arts: Concentration in Design/Technical Production"
  - term: "Women & Gender Studies"