terms:
  - term: "Accounting"
    college: "Business Administration"
  - term: "American Indian Studies"
    college: "Humanities, Arts, Behavioral & Social Sciences"
  - term: "Anthropology"
    college: "Humanities, Arts, Behavioral & Social Sciences"
  - term: "Biological Sciences"
    college: "Science, Technology, Engineering & Math"
  - term: "Business Administration"
    college: "Business Administration"
  - term: "Chemistry & Biochemistry"
    college: "Science, Technology, Engineering & Math"
  - term: "Collections, Delivery, & Access"
    college: "University Library"
  - term: "Communication"
    college: "Humanities, Arts, Behavioral & Social Sciences"
  - term: "Computer Science & Information Systems"
    college: "Science, Technology, Engineering & Math"
  - term: "Economics"
    college: "Humanities, Arts, Behavioral & Social Sciences"
  - term: "Education"
    college: "Education, Health & Human Services"
  - term: "Engineering"
    college: "Science, Technology, Engineering & Math"
  - term: "Environmental Studies"
    college: "Humanities, Arts, Behavioral & Social Sciences"
  - term: "Ethnic Studies"
    college: "Humanities, Arts, Behavioral & Social Sciences"
  - term: "Film Studies"
    college: "Humanities, Arts, Behavioral & Social Sciences"
  - term: "Finance"
    college: "Business Administration"
  - term: "Global Business Management"
    college: "Business Administration"
  - term: "Global Studies"
    college: "Humanities, Arts, Behavioral & Social Sciences"
  - term: "History"
    college: "Humanities, Arts, Behavioral & Social Sciences"
  - term: "Human Development"
    college: "Education, Health & Human Services"
  - term: "Kinesiology"
    college: "Education, Health & Human Services"
  - term: "Liberal Studies"
    college: "Humanities, Arts, Behavioral & Social Sciences"
  - term: "Library Technology Intiatives & Development"
    college: "University Library"
  - term: "Literature and Writing Studies"
    college: "Humanities, Arts, Behavioral & Social Sciences"
  - term: "Management"
    college: "Business Administration"
  - term: "Management information systems"
    college: "Business Administration"
  - term: "Marketing"
    college: "Business Administration"
  - term: "Mathematics"
    college: "Science, Technology, Engineering & Math"
  - term: "Modern Language Studies"
    college: "Humanities, Arts, Behavioral & Social Sciences"
  - term: "Nursing"
    college: "Education, Health & Human Services"
  - term: "Operations & Supply Chain Management"
    college: "Business Administration"
  - term: "Philosophy"
    college: "Humanities, Arts, Behavioral & Social Sciences"
  - term: "Physics"
    college: "Science, Technology, Engineering & Math"
  - term: "Political Science"
    college: "Humanities, Arts, Behavioral & Social Sciences"
  - term: "Psychology"
    college: "Humanities, Arts, Behavioral & Social Sciences"
  - term: "Public Health"
    college: "Education, Health & Human Services"
  - term: "School of Arts -- Art, Media, and Design"
    college: "Humanities, Arts, Behavioral & Social Sciences"
  - term: "School of Arts -- Dance Studies"
    college: "Humanities, Arts, Behavioral & Social Sciences"
  - term: "School of Arts -- Music"
    college: "Humanities, Arts, Behavioral & Social Sciences"
  - term: "School of Arts -- Theatre Arts"
    college: "Humanities, Arts, Behavioral & Social Sciences"
  - term: "Social Sciences"
    college: "Humanities, Arts, Behavioral & Social Sciences"
  - term: "Social Work"
    college: "Education, Health & Human Services"
  - term: "Sociology"
    college: "Humanities, Arts, Behavioral & Social Sciences"
  - term: "Special Collections"
    college: "University Library"
  - term: "Speech-Language Pathology"
    college: "Education, Health & Human Services"
  - term: "Teaching & Learning"
    college: "University Library"
  - term: "User Services"
    college: "University Library"
  - term: "Women's, Gender, and Sexuality Studies"
    college: "Humanities, Arts, Behavioral & Social Sciences"
