terms:
  - term: "Accounting"
    college: "College of Business and Economics"
  - term: "Anthropology"
    college: "College of Natural and Social Sciences"
  - term: "Applied and Advanced Studies in Education"
    college: "Charter College of Education"
  - term: "Art"
    college: "College of Arts and Letters"
  - term: "Asian and Asian-American Studies"
    college: "College of Ethnic Studies"
  - term: "Biological Sciences"
    college: "College of Natural and Social Sciences"
  - term: "Chemistry and Biochemistry"
    college: "College of Natural and Social Sciences"
  - term: "Chicana(o) and Latina(o) Studies"
    college: "College of Ethnic Studies"
  - term: "Child and Family Studies"
    college: "Rongxiang Xu College of Health and Human Services"
  - term: "Civil Engineering"
    college: "College of Engineering, Computer Science, and Technology"
  - term: "Communication Disorders"
    college: "Rongxiang Xu College of Health and Human Services"
  - term: "Communication Studies"
    college: "College of Arts and Letters"
  - term: "Computer Science"
    college: "College of Engineering, Computer Science, and Technology"
  - term: "Criminal Justice and Criminalistics"
    college: "Rongxiang Xu College of Health and Human Services"
  - term: "Curriculum and Instruction"
    college: "Charter College of Education"
  - term: "Economics and Statistics"
    college: "College of Business and Economics"
  - term: "Electrical and Computer Engineering"
    college: "College of Engineering, Computer Science, and Technology"
  - term: "English"
    college: "College of Arts and Letters"
  - term: "Finance, Law and Real Estate"
    college: "College of Business and Economics"
  - term: "Geosciences and Environment"
    college: "College of Natural and Social Sciences"
  - term: "History"
    college: "College of Natural and Social Sciences"
  - term: "Information Systems"
    college: "College of Business and Economics"
  - term: "Intercultural Proficiency"
    college: "Rongxiang Xu College of Health and Human Services"
  - term: "Interdisciplinary Business"
    college: "College of Business and Economics"
  - term: "International Business"
    college: "College of Business and Economics"
  - term: "Kinesiology and Nutritional Science"
    college: "Rongxiang Xu College of Health and Human Services"
  - term: "Latin American Studies"
    college: "College of Natural and Social Sciences"
  - term: "Liberal Studies"
    college: "College of Arts and Letters"
  - term: "Management"
    college: "College of Business and Economics"
  - term: "Marketing"
    college: "College of Business and Economics"
  - term: "Mathematics"
    college: "College of Natural and Social Sciences"
  - term: "Mechanical Engineering"
    college: "College of Engineering, Computer Science, and Technology"
  - term: "Modern Languages and Literatures"
    college: "College of Arts and Letters"
  - term: "Music"
    college: "College of Arts and Letters"
  - term: "Natural Science"
    college: "College of Natural and Social Sciences"
  - term: "Nursing"
    college: "Rongxiang Xu College of Health and Human Services"
  - term: "Pan-African Studies"
    college: "College of Ethnic Studies"
  - term: "Philosophy"
    college: "College of Arts and Letters"
  - term: "Physics and Astronomy"
    college: "College of Natural and Social Sciences"
  - term: "Political Science"
    college: "College of Natural and Social Sciences"
  - term: "Psychology"
    college: "College of Natural and Social Sciences"
  - term: "Public Health"
    college: "Rongxiang Xu College of Health and Human Services"
  - term: "Social Work"
    college: "Rongxiang Xu College of Health and Human Services"
  - term: "Sociology"
    college: "College of Natural and Social Sciences"
  - term: "Special Education and Counseling"
    college: "Charter College of Education"
  - term: "Technology"
    college: "College of Engineering, Computer Science, and Technology"
  - term: "Television, Film, and Media Studies"
    college: "College of Arts and Letters"
  - term: "Theatre and Dance"
    college: "College of Arts and Letters"
  - term: "University Library"
    college: ""
  - term: "Youth Agency Administration"
    college: "Rongxiang Xu College of Health and Human Services"