terms:
  - id: Article
    term: Article
  - id: Book
    term: Book
  - id: Book Chapter
    term: Book Chapter
  - id: Book Review
    term: Book Review
  - id: Conference Proceeding
    term: Conference Proceeding
  - id: Journal Issue
    term: Journal Issue
  - id: Report
    term: Report
  - id: Other
    term: Other
