terms:
  - id: Conference Paper
    term: Conference Paper
  - id: Conference Program
    term: Conference Program
  - id: Poster
    term: Poster
  - id: Interview
    term: Interview
  - id: Presentation
    term: Presentation
  - id: Performance
    term: Performance
