
campus: 'Sacramento'
output_dir: /home/ec2-user/data/harvest/sacramento
external_system: Sac State Scholars
url: https://scholars.csus.edu/view/oai/01CALS_USL/request
set: esploro_esploro
metadataPrefix: esploro
exit_on_error: false
visibility: open
extends: 'sacramento_map.yml'