
campus: 'Sacramento'
work_type: "default"
metadata_file: "mets.xml"
depositor: kcloud@calstate.edu
input_dir: /data/exported/
admin_set_id: 'd217qp48j'

# exit_on_error: when an AIP package encounters an error should the import process end or continue?
# true - ends processing on error
# false - continues processing
exit_on_error: false

# output_level: How much will be output to the shell while running
# quiet - Nothing will be output
# minimal - a running progress bar will be output
# verbose - running progress text will be output
output_level: 'verbose'

include_thumbnail: false

# Enter University eg, California State University, <name>
default_university: California State University, Sacramento

# work map from resource_type.
# values are value_mapped_to_resource_type: Work Type
type_to_work_map:
  Thesis: Thesis
  Masters thesis: Thesis
  Dissertation: Thesis
  Project: Thesis
  Graduate Project: Thesis
  Student Research: Thesis
  Newspaper: Publication
  Journal Issue: Publication
  Article: Publication
  Poster: Publication
  Report: Publication
  Preprint: Publication
  Technical Report: Publication
  Working Paper: Publication
  Other: Thesis
  Abstract: Publication
  Dataset: Dataset
  Text: Publication

# Dublin Core Field Mapping
fields:
  description: # Thesis
    xpath:
      - "/dim:field[@mdschema='dc'][@element='description'][not(@qualifier)]"
      - "/dim:field[@mdschema='dc'][@element='description'][@qualifier='abstract']"
    type: Array
  advisor:
    xpath:
      - "/dim:field[@mdschema='dc'][@element='advisor'][not(@qualifier)]"
      # on second pass move advisor to contributor
      # - "/dim:field[@mdschema='dc'][@element='contributor'][@qualifier='advisor']"
    type: Array
  alternative_title: # Thesis
    xpath:
      - "/dim:field[@mdschema='dc'][@element='title'][@qualifier='alternative']"
    type: Array
  bibliographic_citation:
    xpath:
      - "/dim:field[@mdschema='dc'][@element='identifier'][@qualifier='citation']"
    type: Array
  committee_member: # Thesis
    xpath:
      - "/dim:field[@mdschema='dc'][@element='contributor'][@qualifier='committeemember']"
    type: Array
  contributor:
    xpath:
      - "/dim:field[@mdschema='dc'][@element='contributor'][not(@qualifier)]"
      # on second pass move advisor to contributor
      - "/dim:field[@mdschema='dc'][@element='contributor'][@qualifier='advisor']"
    type: Array
  creator:
    xpath:
      - "/dim:field[@mdschema='dc'][@element='contributor'][@qualifier='author']"
      - "/dim:field[@mdschema='dc'][@element='creator'][not(@qualifier)]"
    type: Array
  date_accessioned:
    xpath:
      - "/dim:field[@mdschema='dc'][@element='date'][@qualifier='accessioned']"
    type: String
  date_created:
    xpath:
      - "/dim:field[@mdschema='dc'][@element='date'][@qualifier='created']"
      - "/dim:field[@mdschema='dc'][@element='date'][not(@qualifier)]"
    type: Array
  date_issued:
    xpath:
      - "/dim:field[@mdschema='dc'][@element='date'][@qualifier='issued']"
    type: Array
  date_modified:
    xpath:
      - "/dim:field[@mdschema='dc'][@element='date'][@qualifier='updated']"
    type: String
  date_submitted: # Thesis
    xpath:
      - "/dim:field[@mdschema='dc'][@element='date'][not(@qualifier)]"
      - "/dim:field[@mdschema='dc'][@element='date'][@qualifier='submitted']"
    type: Array
  date_uploaded:
    xpath:
      - "/dim:field[@mdschema='dc'][@element='date'][@qualifier='available']"
    type: String
  #General description mapping
  #description:
  #  xpath:
  #    - "/dim:field[@mdschema='dc'][@element='description'][not(@qualifier)]"
  #  type: Array
  department:
    xpath:
      - "/dim:field[@mdschema='dc'][@element='description'][@qualifier='sponsorship']"
    type: Array
  embargo_release_date:
    xpath:
      - "/dim:field[@mdschema='dc'][@element='date'][@qualifier='embargountil']"
    type: String
  embargo_terms:
    xpath:
      - "/dim:field[@mdschema='dc'][@element='description'][@qualifier='embargoterms']"
    type: String
  extent: # (Default) Newspaper
    xpath:
      - "/dim:field[@mdschema='dc'][@element='format'][@qualifier='extent']"
    type: Array
  geographical_area: # Thesis
    xpath:
      - "/dim:field[@mdschema='dc'][@element='coverage'][@qualifier='spatial']"
    type: Array
  handle: # Thesis
    xpath:
      - "/dim:field[@mdschema='dc'][@element='identifier'][@qualifier='uri']"
    type: Array
  identifier:
    xpath:
      - "/dim:field[@mdschema='dc'][@element='identifier'][not(@qualifier)]"
      - "/dim:field[@mdschema='dc'][@element='identifier'][@qualifier='isbn']"
      - "/dim:field[@mdschema='dc'][@element='identifier'][@qualifier='issn']"
      - "/dim:field[@mdschema='dc'][@element='identifier'][@qualifier='other']"
      - "/dim:field[@mdschema='dc'][@element='subject'][@qualifier='lcc']"
    type: Array
  is_part_of: # (Default) Newspaper
    xpath:
      - "/dim:field[@mdschema='dc'][@element='relation'][@qualifier='ispartofseries']"
    type: Array
  keyword:
    xpath:
      - "/dim:field[@mdschema='dc'][@element='subject'][@qualifier='lcsh']"
    type: Array
  language:
    xpath:
      - "/dim:field[@mdschema='dc'][@element='language'][not(@qualifier)]"
      - "/dim:field[@mdschema='dc'][@element='language'][@qualifier='iso']"
    type: Array
  license: # (Default) Newspaper
    xpath:
      - "/dim:field[@mdschema='dc'][@element='rights'][@qualifier='license']"
    type: Array
  provenance:
    xpath:
      - "/dim:field[@mdschema='dc'][@element='description'][@qualifier='provenance']"
      - "/dim:field[@mdschema='dc'][@element='provenance'][not(@qualifier)]"
    type: Array
  publisher:
    xpath:
      - "/dim:field[@mdschema='dc'][@element='publisher'][not(@qualifier)]"
    type: Array
  related_url: # (Default) Newspaper
    xpath:
      - "/dim:field[@mdschema='dc'][@element='relation'][@qualifier='uri']"
    type: Array
  resource_type:
    xpath:
      - "/dim:field[@mdschema='dc'][@element='type'][not(@qualifier)]"
      - "/dim:field[@mdschema='dc'][@element='type'][@qualifier='genre']"
      - "/dim:field[@mdschema='dc'][@element='genre'][not(@qualifier)]"
    type: Array
  rights_note:
    xpath:
      - "/dim:field[@mdschema='dc'][@element='rights'][not(@qualifier)]"
    type: Array
  rights_uri:
    xpath:
      - "/dim:field[@mdschema='dc'][@element='rights'][@qualifier='uri']"
    type: Array
  sponsor: # Newspaper
    xpath:
      - "/dim:field[@mdschema='dc'][@element='sponsor'][not(@qualifier)]"
      - "/dim:field[@mdschema='dc'][@element='contributor'][@qualifier='sponsor']"
    type: Array
  subject:
    xpath:
      - "/dim:field[@mdschema='dc'][@element='subject'][not(@qualifier)]"
    type: Array
  time_period: # Thesis
    xpath:
      - "/dim:field[@mdschema='dc'][@element='coverage'][@qualifier='temporal']"
    type: Array
  title:
    xpath:
      - "/dim:field[@mdschema='dc'][@element='title'][not(@qualifier)]"
    type: Array
