# this config campus is used as facet whereas passed in campus is used to assigned managers
campus: 'Fullerton'
subpathwork_type: "default"
input_file: "zenodo.txt"
depositor: admin@calstate.edu
input_dir: /data/exported/zenodo/fullerton
admin_set_id: 'ht24wj40p'

# exit_on_error: when an AIP package encounters an error should the import process end or continue?
# true - ends processing on error
# false - continues processing
exit_on_error: true

# output_level: How much will be output to the shell while running
# quiet - Nothing will be output
# minimal - a running progress bar will be output
# verbose - running progress text will be output
output_level: 'verbose'

include_thumbnail: false

# Enter University eg, California State University, <name>
default_university: California State University, Fullerton

# sandbox URL
#query_url: https://sandbox.zenodo.org/api/records/?q=doi:"QUERY_PARAMETER"
# production URL
query_url: https://zenodo.org/api/records/?q=doi:"QUERY_PARAMETER"

# work map from zenodo type and subtype ex: publication article
# we will default if subtype does not exist
# values are model_resourcetype ex: Publication_Article
# will have model of Publication and resource_type of Article
type_to_work_map:
  publication:
    annotationcollection: Dataset_Collection
    book: Publication_Book
    section: Publication_Book Chapter
    conferencepaper: Publication_Conference Poster
    datamanagementplan: Dataset_Data Paper
    article: Publication_Article
    patent: EducationalResource_Other
    preprint: Publication_Research Paper
    deliverable: Thesis_Project
    milestone: Thesis_Project
    proposal: EducationalResource_Other
    report: Publication_Research Paper
    softwaredocumentation: Dataset_Software
    taxonomictreatment: Publication_Research Paper
    technicalnote: Dataset_Text
    thesis: Thesis_Abstract
    workingpaper: Publication_Research Paper
    other: EducationalResource_Other
  presentation:
    default: Publication_Presentation
  poster:
    default: Publication_Article
  dataset: 
    default: Dataset_Dataset
  image:
    figure: Dataset_Image
    plot: Dataset_Image
    drawing: Dataset_Image
    diagram: Dataset_Image
    photo: Dataset_Image
    other: Dataset_Image
  video:
    default: EducationalResource_Video - Instructional
  software:
    default: Dataset_Software
  lesson:
    default: EducationalResource_Online Course Module
  physicalobject:
    default: Dataset_Physical Object
  other:
    default: EducationalResource_Other

access_right:
  open: open
  embargoed: embargo
  restricted: campus 
  closed: restricted

# composite person mapping that consists name, affiliation, orcid
person_fields:
  creators: creator
  contributors: contributor


# one to one mapping with single value or array
direct_map_fields:
  doi: doi
  publication_date: date_created
  title: title
  description: description
  language: language
  notes: description_note
  # array values
  keywords: keyword
  references: bibliographic_citation

hash_map_fields:
  imprint:
    publisher: publisher
    isbn: isbn
 
hash_array_map_fields:
  subjects:
    term: subject

work_specific_hash_map_fields:
  Publication:
    journal:
      title: journal_title
      volume: volume
      issue: issue
      pages: pages
    meeting:
      title: conference_title
