default: &default
  adapter: <%= ENV.fetch("DATABASE_ADAPTER", "postgresql") %>
  encoding: unicode
  username: <%= ENV.fetch("DATABASE_USER", "csusm_postgres_dev") %>
  password: <%= ENV.fetch("DATABASE_PASSWORD", "demo") %>
  host: <%= ENV.fetch("DATABASE_HOST", "localhost") %>
  port: <%= ENV.fetch("DATABASE_PORT", 5432) %>
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: <%= ENV.fetch("DATABASE_NAME", "csusm_postgres_development") %>
test:
  <<: *default
  database: <%= ENV.fetch("DATABASE_TEST_NAME", "csusm_postgres_test") %>
production:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>
  database: <%= ENV['DATABASE_NAME'] %>
  username: <%= ENV['DATABASE_USER'] %>
  password: <%= ENV['DATABASE_PASSWORD'] %>
