# taken from minetype_fu.rb from https://github.com/mattetti/mimetype-fu/tree/master and simplify it
# EXTENSIONS => CONTENT TYPE
\"669\": Audio
3ds: Image
3g2: Video
3gp: Video
3gpp: Video
aac: Audio
ac3: Audio
ag: Image
aif: Audio
aifc: Audio
aiff: Audio
amr: Audio
ape: Audio
arw: Image
asf: Video
asx: Audio
au: Audio
avi: Video
awb: Audio
bmp: Image
cgm: Image
cr2: Image
crw: Image
cur: Image
dcr: Image
dds: Image
dgn: Image
divx: Video
djv: Image
djvu: Image
dl: Video
dng: Image
dv: Video
dwg: Image
dxf: Image
ecelp4800: Audio
ecelp7470: Audio
ecelp9600: Audio
emf: Image
eol: Audio
eps: Image
epsf: Image
epsi: Image
evc: Audio
fig: Image
fits: Image
flac: Audio
flc: Video
fli: Video
g3: Image
gif: Image
gif: Image
gl: Video
icb: Image
icns: Image
ico: Image
ief: Image
iff: Image
it: Audio
j2k: Image
jng: Image
jp2: Image
jpc: Image
jpe: Image
jpeg: Image
jpf: Image
jpg: Image
jpm: Image
jpx: Image
k25: Image
kar: Audio
l16: Audio
lvp: Audio
lwo: Image
lwob: Image
lws: Image
m15: Audio
m2t: Video
m3u: Audio
m4a: Audio
m4b: Audio
m4u: Video
m4v: Video
mid: Audio
midi: Audio
minipsf: Audio
mj2: Video
mjp2: Video
mka: Audio
mkv: Video
mng: Video
mod: Audio
moov: Video
mov: Video
movie: Video
\"mp+\": Audio
mp2: Audio
mp2: Video
mp3: Audio
mp3g: Video
mp4: Video
mpc: Audio
mpe: Video
mpeg: Video
mpg: Video
mpga: Audio
mrw: Image
msod: Image
mtm: Audio
mxmf: Audio
mxu: Video
nef: Image
nim: Video
nsv: Video
oga: Audio
ogm: Video
ogv: Video
orf: Image
pbm: Image
pcd: Image
pef: Image
pgb: Image
pgm: Image
pict: Image
pict1: Image
pict2: Image
plj: Audio
pls: Audio
png: Image
pnm: Image
pntg: Image
ppm: Image
psd: Image
psf: Audio
psflib: Audio
psid: Audio
psp: Image
pspImage: Image
qcp: Audio
qif: Image
qt: Video
qtif: Image
qtvr: Video
ra: Audio
raf: Image
ram: Audio
ras: Image
raw: Image
rax: Audio
rgb: Image
rle: Image
rp: Image
rv: Video
rvx: Video
s11: Video
s14: Video
s1j: Image
s1m: Audio
s1n: Image
s1q: Video
s3m: Audio
sgi: Image
sgif: Image
sjp: Image
sjpg: Image
smo: Video
smov: Video
smp: Audio
smp3: Audio
smpg: Video
smv: Audio
snd: Audio
spn: Image
spng: Image
spx: Audio
sr2: Image
srf: Image
ssw: Video
sswf: Video
sun: Image
svg: Image
svgz: Image
tga: Image
tif: Image
tiff: Image
tpic: Image
tta: Audio
vbk: Audio
vda: Image
viv: Video
vivo: Video
vlc: Audio
vob: Video
voc: Audio
wav: Audio
wax: Audio
wbmp: Image
wm: Video
wma: Audio
wmf: Image
wmv: Video
wmx: Audio
wv: Audio
wvc: Audio
wvp: Audio
wvx: Audio
x3f: Image
xbm: Image
xcf: Image
xi: Audio
xm: Audio
xpm: Image
xwd: Image
