development:
<<<<<<< Updated upstream
  host: <%= ENV.fetch('REDIS_SERVER', 'localhost') %>
  port: 6379
=======
  host: <%= ENV.fetch('REDIS_HOST', 'localhost') %>
<<<<<<< Updated upstream
  port: <%= ENV.fetch('REDIS_PORT', 6379) %>
>>>>>>> Stashed changes
test:
  host: <%= ENV.fetch('REDIS_SERVER', 'localhost') %>
  port: 6379
production:
<<<<<<< Updated upstream
  host: <%= ENV['REDIS_SERVER'] %>
  port: <%= ENV['REDIS_PORT'] %>
=======
  host: <%= ENV.fetch('REDIS_HOST', 'localhost') %>
  port: <%= ENV.fetch('REDIS_PORT', 6379) %>
=======
  port: 6379
test:
  host: <%= ENV.fetch('REDIS_HOST', 'localhost') %>
  port: 6379
production:
  host: <%= ENV['REDIS_HOST'] %>
  port: <%= ENV['REDIS_PORT'] %>
>>>>>>> Stashed changes
>>>>>>> Stashed changes
