development:
  host: <%= ENV['REDIS_SERVER'] || 'localhost' %>
  port: <%= ENV['REDIS_PORT'] || 6379 %>
test:
  host: <%= ENV['REDIS_SERVER'] || 'localhost' %>
  port: <%= ENV['REDIS_PORT'] || 6379 %>
production:
  host: <%= ENV['REDIS_SERVER'] || 'localhost' %>
  port: <%= ENV['REDIS_PORT'] || 6379 %>
  db: <%= ENV['REDIS_DB'] || 0 %>
