# production

cr56n096b: # east bay
  visibility: open
  visibility_during_embargo: restricted
  visibility_after_embargo: open
  default_type: Masters Thesis

02870v844: # fullerton
  visibility: open
  visibility_during_embargo: restricted
  visibility_after_embargo: open
  default_type: Masters Thesis

zk51vg76b: # los angeles
  visibility: campus
  visibility_during_embargo: restricted
  visibility_after_embargo: campus
  default_type: Masters Thesis

zc77sq08x: # northridge
  visibility: open
  visibility_during_embargo: restricted
  visibility_after_embargo: open
  default_type: Masters Thesis

3b5918567: # pomona
  visibility: open
  visibility_during_embargo: restricted
  visibility_after_embargo: open
  default_type: Masters Thesis

rr171x20k: # stanislaus
  visibility: open
  visibility_during_embargo: restricted
  visibility_after_embargo: open
  default_type: Masters Thesis

# test

4b29b635b: # northridge
  visibility: open
  visibility_during_embargo: restricted
  visibility_after_embargo: open
  default_type: Masters Thesis

cc08hg00q: # fullerton
  visibility: open
  visibility_during_embargo: restricted
  visibility_after_embargo: open
  default_type: Masters Thesis