facets:
  resource_type:
    limit: 5
  campus:
    limit: 10
  department:
    limit: 5
  degree_level:
    limit: 5
  date_issued_year:
    range: true
    include_in_advanced_search: false
    sort: 'index'
  file_type:
    limit: 4

advanced_search:
  - title
  - creator
  - publisher
  - keyword
  - subject
  - discipline
  - handle
  
models:
  - thesis
  - project
  - presentation
  - publication
  - dataset
  - educational_resource

google_analytics_id: 'G-3GBP412H1C'
