# Generated by hyrax:models:install
#
# Piggy-back campus value from work
#
class FileSet < ActiveFedora::Base
  property :glacier_location, predicate: ::RDF::URI.intern('https://cal-state.edu/file_set/glacier_location'), multiple: true do |index|
    index.as :stored_searchable
  end

  attr_accessor :campus

  include ::Hyrax::FileSetBehavior
  include ::Hydra::AccessControls::CampusVisibility

  def campus
    # get campus name from work
    return parent&.campus unless parent&.campus.blank?

    # nope? use attribute, if set
    @campus
  end
end
