
# test server

nv9353847: # northridge
  visibility: open
  visibility_during_embargo: restricted
  visibility_after_embargo: open
  default_type: Masters Thesis
jw827c041: # east bay
  visibility: open
  visibility_during_embargo: campus
  visibility_after_embargo: open
  default_type: Masters Thesis
12579t09n: # los angeles
  visibility: private
  default_type: Masters Thesis

# production

cr56n096b: # east bay
  visibility: open
  visibility_during_embargo: restricted
  visibility_after_embargo: open
  default_type: Masters Thesis

3b5918567: # pomona
  visibility: open
  visibility_during_embargo: restricted
  visibility_after_embargo: open
  default_type: Masters Thesis

zk51vg76b: # los angeles
  visibility: campus
  visibility_during_embargo: restricted
  visibility_after_embargo: campus
  default_type: Masters Thesis